[tbon]
interface_hint = "ib0"

[resource]
path = "/users/pa23/goumas/kkats/flurm/aris/conf.d/R"
scheduling = "/users/pa23/goumas/kkats/flurm/aris/conf.d/aris.json"

[ingest.validator]
disable = true

[sched-fluxion-resource]
load-allowlist = "node,socket,core"
match-format = "rv1"
